server:
  port: 8080
  
#management:
#  security:
#    enabled: false #关掉安全认证
 #   user:
 #     name: root
#      password: root
#  port: 8088 #管理端口调整成8088
#  context-path: /monitor #actuator的访问路径
  
endpoints:
  shutdown:
    enabled: true  

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/god?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: password
        # 使用druid数据源	
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:biz/mapper/*.xml
  type-aliases-package: com.xiehou.share.springboot.dao